spring:
  datasource:
    password: password
    username: username
    url: jdbc:postgresql://localhost:5432/song_db
  jpa:
    hibernate:
      ddl-auto: create
  application:
    name: song-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
