spring:
  datasource:
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    url: ${DB_URL_SONG}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  application:
    name: song-service
eureka:
  client:
    service-url:
      defaultZone: http://cloud-eureka-discovery-service:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
